/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.14.1/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.10.0"
}

rootProject.name = "ctool4k"
include("ctool4k-dependencies")

include("ctool4k-parent")
include("ctool4k-parent:ctool4k-component")
include("ctool4k-parent:ctool4k-component:ctool4k-definition")
include("ctool4k-parent:ctool4k-component:ctool4k-web")

include("app")
